CDLUC3/ezid

- .gitignore
- code/util.py
- settings/ezid.conf
- settings/staging.py
- Includes fix for 10.3 bug
- Loading shoulders locally in EZID
> Fixing 10.3 bug

- settings/ezid.conf
Included configs for communication with the Handle systems
> Handle test configs

- impl/oai.py
This resolves remaining issues with OAI service
> Fixes #268

- templates/index.html
Added banner to display the outage warning
> Added banner to display the outage warning

- ezidapp/management/commands/proc-download.py
Corrects an issue in proc_download when requesting xml format.
> Don't write bytes to a text file!

- .gitignore
- impl/api.py
- impl/ui.py
- impl/userauth.py
Addresses problem of unhandled exceptions from malformed requests to `/login`
> Fix 327 login

- impl/api.py
Adjusted handing of error responses to avoid triggering email notification of invalid login attempts
> close #327

- ezidapp/management/commands/proc-crossref.py
- impl/crossref.py
> Add support for Crossref v5.X

- impl/ui_account.py
Fix issues with resetting user password
> Fixes 341, adds some type hinting

- impl/datacite_xml.py
- impl/form_objects.py
- templates/create/_datacite_date.html
Resolves the following issue/s:
- #432 
- #433
> Feature 432 433 doi registration

- .gitignore
- ezidapp/management/commands/proc-crossref.py
- ezidapp/models/identifier.py
Fix issues with not being able to send error emails to Crossref owners
#397
> Fix issues with not being able to send error emails to Crossref owners

- ezidapp/management/commands/proc-cleanup-async-queues.py
Resolves issues with continuous looping of the async job
> Bug cleanup queue fix

- ezidapp/management/commands/shoulder-update-organization.py
@datadavev @rushirajnenuji Hi  Dave and Rushiraji,
Please review. 
Thank you
Jing
> remove repeated upper() on shoulder

- requirements-dev.txt
- requirements.txt
Upgrade python packages based on dependabot recommendations.
> upgrade python packages

- settings/settings.py.j2
This fixes some config variables that got lost in a merge.
> Add missing settings that got lost in the merges

- requirements-dev.txt
- requirements.txt
@sfisher Hi Scott, 
This is to upgrade PyMySQL and aiomysql to resolve [PyMySQL SQL Injection vulnerability](https://github.com/CDLUC3/ezid/security/dependabot/131).
Please review and let me know if you have quesitons.
Thank you
Jing
> upgrade PyMySQL and aiomysql

- package-lock.json
- package.json
> Revert "Bump send and browser-sync"

- impl/api.py
- impl/form_objects.py
- ui_tags/templatetags/manage_form_tags.py
This is to fix deprecation warnings reported during Python 311 upgrade from `python -Wd manage.py runserver` command.
Deprecation warnings include:
* using deprecated cgi library
* using invalid escape sequence
Warning details:
```
/Users/jjiang/my_dev_space/ezid-dev/ezid/impl/api.py:86: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
import cgi
/Users/jjiang/my_dev_space/ezid-dev/ezid/impl/form_objects.py:75: DeprecationWarning: invalid escape sequence '\d'
REGEX_4DIGITYEAR = '^(\d{4}|\(:unac\)|\(:unal\)|\(:unap\)|\(:unas\)|\(:unav\)|\
/Users/jjiang/my_dev_space/ezid-dev/ezid/impl/form_objects.py:77: DeprecationWarning: invalid escape sequence '\d'
REGEX_GEOPOINT = '-?(\d+(\.\d*)?|\.\d+)$' …
```
> 747 fix deprecations

- ezidapp/management/commands/opensearch-delete.py
- ezidapp/management/commands/proc-cleanup-async-queues_v2.py
- ezidapp/management/commands/proc-link-checker-update.py
- impl/open_search_doc.py
- tests/test_open_search_doc.py
Merge develop to main for:
* Refactor OpenSearch delete
* Refactor proc-cleanup-async-queues
> Merge develop to main

- dev/includes/home-banner.html
- dev/layout_create.html
- dev/layout_home.html
- dev/legacy-scss/variables.scss
- dev/scss/_fieldsets.scss
- gulpfile.js
- static_src/stylesheets/main2.min.css
- templates/includes/simple_id_type.html
- templates/index.html
This changes the things noted in https://github.com/CDLUC3/ezid/issues/541 except for the page reloading and form switching which will be a lot more complicated based on the current structure.  I may make a separate PR for that and probably do it with some AJAX and need to reorganize the form some.
It also adds to the gulp workflow so that "gulp build" copies the compiled file over where it belongs so I can see and modify the SCSS changes without more manual work.
For the "contrast" item, I choose darker colors of teal which should give more contrast with the white text, though there is still a gradient on the button.
> VPAT fixes for homepage ticket #541

- poetry.lock
- pyproject.toml
@sfisher Hi Scott, 
This is to update Django from 4.2.16 to 4.2.17. Please review and let me know if you have questions.
Thank you
Jing
> update Django to 4.2.17

- templates/doc/apidoc.2.html
- templates/doc/apidoc.html
See #799 .  Fixes these four dead links.
> Update broken links in API docs
