ezidapp/management/commands/proc-datacite.py, ezidapp/management/commands/proc_base.py
Added a custom exception for cases where datacite reports an error, which in turn is used to flag a task as a permanent error. Closes #205
=> Py3 bug/205

ezidapp/management/commands/proc-binder.py
Probably fixes #206, directly addresses log messages like:
```
eb 15 09:55:31 uc3-ezidui02x2-stg ezid-proc-errorlog: DEBUG ezidapp.management.commands.proc_base proc_base 2538 140498724128576 Binder: Processing task: update
Feb 15 09:55:31 uc3-ezidui02x2-stg ezid-proc-errorlog: ERROR ezidapp.management.commands.proc_base proc_base 2538 140498724128576 Binder: Task registration error
Feb 15 09:55:31 uc3-ezidui02x2-stg ezid-proc-errorlog: Traceback (most recent call last):
Feb 15 09:55:31 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 99, in run
Feb 15 09:55:31 uc3-ezidui02x2-stg ezid-proc-errorlog: self.do_task(task_model)
Feb 15 09:55:31 uc3-ezidui02x2-stg ezid-proc-errorlog: File …
```
=> Typo in model reference. Fixes #206

ezidapp/management/commands/proc_base.py, settings/settings.py.j2
Adjust `proc_base` by:
1. Gracefully handle termination or interruption of the background process
2. Don't reset database connection until at least `settings.DAEMONS_IDLE_DB_RECONNECT`
The later reduces the db connect/reconnect chatter and allows for much shorter sleep cycles of the daemons, which in turn allows for improved responsiveness of background jobs, e.g. `DAEMONS_IDLE_SLEEP` can be set to 1 instead of the default 60.
=> Proc refine

ezidapp/management/commands/proc-expunge.py
Since expunge is now a mgmt cmd, we can delete test identifiers
directly instead of going through the REST API.
=> proc-expunge: Delete identifiers directly

ezidapp/management/commands/proc-link-checker.py
This method was commented out which caused an error in logging which in turned crashed linkchecker since it was expecting this method to be available.
=> Uncomment s() method

impl/api.py
Corrects an oversight in handling response codes. Successful create ops should return 201.
=> fix(#334): create should return 201 status

ezidapp/management/commands/proc-crossref.py, ezidapp/management/commands/proc_base.py, impl/noid_egg.py, settings/settings.py.j2
Fix: #108. A timeout was not set in http client connections using in the background processing for crossref and binder.
=> Fix 108 timeout

ezidapp/management/commands/proc-datacite.py
@datadavev @rushirajnenuji Hi Dave and Rushiraj,
The `formRecord` function has two options to get the profile info:
1. through the "profile" parameter of the function
2. through the metadata["_p"] data field
Since the caller `uploadMetadata` does not use the profile parameter, option 2 should be considered.
This change still needs comprehensive tests to cover all datacite related profiles including:
* datacite
* dc
This change should not affect other profiles but tests are also needed.
Test data should cover both name:value and XML formats.
Please let me know if you have questions.
Thank you
Jing
=> pass profile through metadata['_p']

ezidapp/management/commands/diag-create-missing-minters-tmp-fix.py
@rushirajnenuji Hi Rushiraji, 
This is a  copy of the `diag-create-missing-minters.py` script with the 2nd parameter `shoulder_str` removed from the ` impl.nog.minter.create_minter_database` function.
```
% diff  diag-create-missing-minters-tmp-fix.py  diag-create-missing-minters.py        
106c106
<                 impl.nog.minter.create_minter_database(s.prefix)
---
>                 impl.nog.minter.create_minter_database(s.prefix, shoulder_str)
```
Please review.
Thank you
Jing
=> fix db-path for diag-create-missing-minters

ezidapp/management/commands/diag-create-missing-minters-tmp-fix.py
@rushirajnenuji Hi Rushiraj,
While testing the create missing minters script on stage, I found additional issue:
current script failed on the following `shoulder.minter` which contains a dot in the  shoulder string 's6.caida':
- 'https://n2t.net/a/ezid/m/ark/d1986/s6.caida',
- 'https://n2t.net/a/ezid/m/ark/81986/s6.caida',
I changed the script to use this build-in function which is used by mint identifier API : - impl.nog.bdb.get_bdb_path_by_shoulder_model(shoulder_model) to handle this.
Please review and let me know if you have qeustions.
Thank you
Jing
=> Bug fix to handle shoulder string with dot

requirements-dev.txt, requirements.txt
@sfisher @rushirajnenuji Hi Scott and Rushiraj,
This is to upgrade Jinja2 to 3.1.3. The ezid-stg is running on v3.2.4rc0 with this update. Please take a look and let me know if you have quesitons.
Thank you
Jing
=> upgrade Jinja2 to 3.1.3

package-lock.json
@sfisher Hi Scott, 
I am merging the develop branch to main for "Bump ws, engine.io-client, engine.io and socket.io-adapter" based on Dependabot pull request. 
* No issues running `gulp` and `gulp build`. 
* There are minor changes to the `ui_library/css/main2.min.css` file. We have decided not to copy this stylesheet to the EZID code base.
* No changes to the `ui_library/js/main2.min.js` file
* affected libraries are not used directly by EZID UI
Tests performed on ezid-stg:
* GitHub Action/CI tests - passed
* function tests by running the `python verify_ezid_after_patching.py -e stg` command - passed
* UI tests by running the `python ezid_ui_tests.py -e stg` - passed
Please review. 
Thank you
Jing
=> Merge Develop to main for updating package-lock.json

.github/workflows/main.yml, tests/test_api_util.py, tests/test_form_objects.py
This is to update the github action to use Python 3.11 for EZID unit and integration tests. 
A few unit tests are added for functions that use deprecated interfaces (reported by the Python interpreter with option -Wd). Fixes to these functions will be implemented in the near future.
Please review and let me know if you have questions.
Thank you
Jing
=> 468 python 311 upgrade

ezidapp/management/commands/proc-link-checker-update.py, impl/open_search_doc.py, tests/test_open_search_doc.py
(and OpenSearch update_time) from link checker.
1) only updates the db/opensearch if values are changed
2) now OpenSearch link checker update takes the unix time in function signature
3) updated tests to be correct for changed method in opensearch doc class
closes https://github.com/CDLUC3/ezid/issues/752
=> Updates the SearchIdentifier updateTime 

ezidapp/management/commands/proc-cleanup-async-queues_v2.py
This script is derived from the `proc-cleanup-async-queues.py` and will be used for async queue data cleanup.
The command takes 3 parameters:
* page size: optional which will be used to test database performance on different batch sizes
* updated_from and updated_to: required when we work on batch data cleanup
The sleep logic when the queryset reaches to its end (`if not refIdsQS`) may need refactoring for production implementation. This will affect when to rerun the job.
For the batch data cleanup, we should terminate the process when the queryset reaches to its end.
```
if not refIdsQS:
break
```
Please review and let me know if you have questions.
=> add proc-cleanup-async-queues_v2.py with data range

ezidapp/management/commands/proc-cleanup-async-queues_v2.py, impl/ui.py
Here are the changes:
* replace the wrapper function `django.core.mail.send_mail()` which does not support `reply_to` with the lower level class EmailMessage. We need the the `reply_to` field to store user entered email which will be used to generate help desk email
* bug fix to the `proc-cleanup-async-queues_v2.py` script - the `last_id = refId.pk` statement should be inside the loop otherwise "None" error will be generated when query returns no results.
Please review and let me know if you have questions.
Thank you
Jing
=> 774 fix contact form email issue

ezidapp/management/commands/proc-cleanup-async-queues_v2.py
The last ID and the upper value of the time range need to be reset after finishing current date/time range. This part of logic (using current date/time to calculate date/time range) will be used by the regular async queue cleanup job. 
Please review.
Thank you
Jing
=> 727 fix cleanup async queues

impl/form_objects.py
After the dash like `en-US` it used to only allow upper case letters.
This could be either.
I looked at the DataCite docs and it mentions [IETF BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag), [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).  I looked over these codes and it appears that this regex will cover it (I don't see any non-alphabetic characters in either part).
It looks like the error message is ok: `ERR_LANGUAGE = _("Must be a valid language code (IETF BCP 47 or ISO 639-1)")`
I didn't see it come up in the documentation elsewhere when I searched.
=> Change regular expression to allow both upper and lower case letters in language code

ezidapp/management/commands/opensearch-update.py
See #792 for problems with some modified records deposited in the last few weeks.  They had thousands of authors or more and I guess EZID hasn't seen records of this size until now.
I don't know how to test this really anywhere but production since the other environments don't contain the huge records.
But I manually modified the page size on production and verified it makes the error go away.  Script called like.
```
python -u manage.py opensearch-update --updated_since=2024-11-04T00:00:00Z
```
I have a copy in `~/tmp/ezid` so it could be checked out and pulled there and run there without affecting the production deployment.
=> Fix for records that are too large by reducing the bulk update size

ezidapp/management/commands/proc-cleanup-async-queues.py, ezidapp/management/commands/proc-cleanup-async-queues_v1.py
@sfisher Hi Scott, 
This is to replace the `proc-cleanup-async-queues.py` script with `proc-cleanup-async-queues_v2.py`. A copy of the original script is saved as `proc-cleanup-async-queues_v1.py`. The `_v1` and `_v2` can be removed eventually after the refactored job runs stably in the production environment. 
Please review. Thank you.
Jing
=> 727 test cleanup async queues 2

impl/ui_home.py, settings/urls.py, static_src/javascripts/simple_create_ajax.js, templates/create/_home_demo_form.html, templates/includes/simple_id_type.html, templates/index.html
This is a continuation of #541 .
This makes it so that switching to ARK or DOI changes the form below without reloading the page.
It also includes some of the previous fixes for VPAT stuff.  If you accept that previous PR first then the diff will only show the things actually changed for this PR.
This now moves the form to a partial.  It adds some actions controller actions for handling AJAX. It adds javascript for triggering the AJAX calls and then re-renders the new content into the appropriate div for the new form.
I also had to add some hidden fields and leave the radio buttons for the ARk/DOI outside the main form since it will get erased when the form is re-rendered so that it needs to stay outside the main form.
I took a while to figure out why the normal one didn't work and …
=> Switching form for homepage without reloading page

dev/scss/_home.scss, static_src/stylesheets/main2.min.css
from the "see how easy it is" demo.
It looks a lot cleaner without it.
Tested on dev, also and arrow is gone. :-)
=> Remove the background hint arrow

ezidapp/management/commands/proc-link-checker.py, settings/settings.py.j2
This allows exclusion by regex, which would be the same as shoulder if using a regex like `^ark:/13030/c8` which anchors at the beginning of the identifier string.  It allows us flexibility if we need to do more involved exclusion later but works for this use case.
I tried to follow the patterns already being used in these files.
I'm not sure about how to test this out, so I'll mark as a draft PR until we can discuss and I can run through that testing.
I'm also not sure about reporting from the link checker.  I think this is an unknown task right now (about how reporting should be affected) and my belong in it's own task if we're overhauling it (and some users are already excluded and I'm not sure how that works with reporting).
=> Refactor link checker to enable exclusion by shoulder

templates/demo/advanced.html, templates/demo/simple.html
See https://github.com/CDLUC3/ezid/issues/918 .
This required restructuring of the page and using new "fake" bootstrap styles since the previous version was out of order and there was no easy way to set tabindexes correctly with the different portions of the page and how it changes.
It was already redone for the "Create" pages, but made the same changes to the "demo" pages.
There are still some problems on these pages which is choosing different identifier types reloads the page and doesn't go back to the same place.  That'll be the next change which I'll probably base off this PR since that'll be the new version of the page.
May want to wait to review until I get that done since you can look at both at once.
=> Tabs are out of order

impl/ui_create.py, static_src/javascripts/advanced_create.js, static_src/javascripts/simple_create.js, templates/create/advanced.html, templates/create/simple.html, templates/demo/advanced.html, templates/demo/simple.html
I'm bundling all the "change of context" errors within this PR:
- https://github.com/CDLUC3/ezid/issues/919
- https://github.com/CDLUC3/ezid/issues/920
The problem is that the page reloads to change the page content (the old style way) and the place in the page gets lost when using the keyboard.  This applies to the 4 pages demo/simple, demo/advanced, create/simple, create/advanced.
The controls that change the page content are 1) going from Ark to DOI or DOI to ARK, 2) or changing the profile.  Both these reload the page for new contents but weren't going back to the same place in the page afterward in some cases.
Now we should observe that it goes back to where it came from afterward.
A longer term fix may be either using something like AJAX and unobtrusive javascript to reload parts of …
=> Unexpected change of context errors

poetry.lock, pyproject.toml
This is to upgrade Django 4.2.24 to address security issue #941. The branch was created from the main branch which contains two merge related commits that the develop branch does not have. I was trying to merge the main branch to the develop branch to have it in sync with main. However the new branch protection rule "no merge without pull request" blocked it. I hope the 2 merge related commits will not cause issue when we merge the develop branch to the main for production deployment.
UI and functional tests all look good on ezid-stg with a testing tag `test-django-4.2.24`.
Please take a look and let me know if you have questions.
Jing
=> 941 upgrade django 4.2.24
